#!/bin/bash
# savebat - Save my battery!
# Description: XFCE bash loop to warn user when battery reaches 90% of charge or is bellow 20%.
# Version: 0.2

#Copyright (c) 2015 Javier O. Cordero Pérez <javier@imaginary.tech>
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#f this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.

#  PROGRAM START.
$"notify-send" "Save my battery!" "Program started."
# Enter infinite loop.
while :
do
	# Get current power level.
	POWERLVL="$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E percentage: | tr -cd [:digit:])"
	STATE="$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E state: | awk '{print $2}')"
	# If level charging and above 80, send alert!
	if [ "$POWERLVL" -ge 90 -a "$STATE" == "charging" ]
	then ($"notify-send" "Save my battery!" "Charge reached $POWERLVL%! Time to disconnect.")
		play -q snd/sound.ogg &
		FREQ=15.4
	elif [ "$POWERLVL" -le 22 -a "$STATE" == "discharging" ]
	then ($"notify-send" "Save my battery!" "Charge reached $POWERLVL%! Time to plug-in.")
		play -q snd/alert.ogg &
		FREQ=12
	else FREQ=60
	fi

	# Debug itteration.
	echo $POWERLVL", "$STATE

	# Wait x seconds before reattempt.
	sleep $FREQ
done
